### ISSUE TITLE
fish shell: error when running xpanes --ssh server{1..4}

### ISSUE THREAD

**Issue by bogdanstoica35** [greymd/tmux-xpanes#104]
I'm using xpanes on MacOS Mojave. I also use fish shell as the default shell. I'm trying to execute a command like this:

xpanes --ssh server{1..4}. It returns error: `ssh: Could not resolve hostname server1..4: -65540`

Same action works just fine if I use bash as the default shell or sh or zsh

Installed versions: xpanes 3.1.0, fish, version 2.7.1.

I thought initially that the issue is related because of using iTerm instead of the default MacOS terminal. I tried with both of them and none works as long as I have fish shell. If I switch to bash, everything works just fine.

Any clues?!

**Comment by greymd** [comment]
Hi @bogdanstoica35 ,
I guess this is caused by the fish's behavior.
As far as I know, fish does not support brace expansion with range like `{1..4}` ([link](https://github.com/fish-shell/fish-shell/issues/1556)).

Could you try `xpanes --ssh server{1,2,3,4}` or `xpanes --ssh server(seq 4)` ?

**Comment by bogdanstoica35** [comment]
Thanks for the tip. I tried with the 2nd option `server(seq 4)` and it works like a charm.
