### ISSUE TITLE
Kudos!

### ISSUE THREAD

**Issue by dzg** [greymd/tmux-xpanes#105]
No issue, I just felt the need to say that this is absolutely amazing!

One question, or feature request: Is there any way to delay the launch of command in each pane? (Similar to `parallel --delay {sec}`) 

It would be great to be able to specify a "time offset" so that they don't all start at once.

Thanks!

**Comment by greymd** [comment]
Hi @dzg , thank you for using xpanes !

`xpanes` does not have such the feature.
But I understand how `parallel`'s `--delay` is useful and the idea is worth implementing 👍 
After the release of next version (I am working on `3.2.0` now), I will consider to to implement it.

Here is the workaround by the way.

### Workaround

Edit `xpanes` v3.1.0
1. Insert `[[ -z "${DELAY}" ]] && sleep "${DELAY}"` at line 607.
2. Set shell variable `DELAY`
3. Execute

```diff
diff --git a/bin/xpanes b/bin/xpanes
index a588d0b..0657a41 100755
--- a/bin/xpanes
+++ b/bin/xpanes
@@ -607,6 +607,7 @@ xpns_send_commands() {
   local _pane_index
   for arg in "$@"
   do
+    [[ -n "${DELAY}" ]] && sleep "${DELAY}"
     _pane_index=$(( _index + _index_offset ))
     ${TMUX_XPANES_EXEC} send-keys -t "${_window_name}.${_pane_index}" "${_cmd//${_repstr}/${arg}}" C-m
     _index=$(( _index + 1 ))
```

```
DELAY=1 xpanes -c 'echo {}' A B C D E F
```

It is itself easy to implement but it does not work with particular options like `-s`.
Refactoring is required 😭

**Comment by dzg** [comment]
That's great, thanks!

One more question ... say I want open 8 panes with command A, plus one more with command B. I tried many ways and couldn't get it to work. (I'm not that smart.)

This worked for simple test:
```
xpanes -e `for _ in {1..4}; do echo cmdA; done` cmdB
```

But what if my command A is long, like:
```
'/Volumes/Common/_Automation/nodesTesting/script.py' '/Volumes/Work/_Automation/queue/rendering' --tick 5
```

I tried 
```
c="'/Volumes/Common/_Automation/nodesTesting/zGardener-v4.py' '/Volumes/Work/_Automation/queue/3_rendering' --tick 5"
```
and then
```
xpanes -e `for _ in {1..3}; do echo $c; done` cmdB
```

but this did not work

I also tried 
```
xpanes -e `for _ in {1..3}; do echo "$c"; done`  cmdB
```

... and also `$(...)` and `printf` and so on...

Thanks!

**Comment by greymd** [comment]
As far as I know, the result of [command substitution](https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html) is purely separated by white space and each field is recognized as the individual argument.

To solve it with bash feature, using `eval` is one of the idea.

#### Escaping & eval
```
eval xpanes --debug `for _ in {1..3}; do echo \"$c\"; done` cmdB
```

On the other hand, `xpanes` has the feature for such the situation.

#### Use `-n` option
```
xpanes -en 4 `for _ in {1..3}; do echo "$c"; done`  cmdB
```

#### Use pipe mode
```
{ for _ in {1..3}; do echo "$c"; done; echo cmdB; } | xpanes -e
```

Thanks!

**Comment by dzg** [comment]
Thanks for helping me!

The `eval` example works! (However I had to use `-e` option)

But you should know, when I do:
```
c=cmdA
xpanes -en 4 `for _ in {1..3}; do echo "$c"; done`  cmdB
```
I get only ONE pane with the command `cmdA cmdA cmdA cmdB`.
I do not get 4 panes.

Your pipe example also works, but it shows me:
```
xpanes:Warning: Attached session is required for 'Pipe mode'.
open terminal failed: not a terminal
xpanes:Recovery: Execute below command line to re-attach the new session.

tmux -S /Users/dang/.cache/xpanes/socket attach-session -t xpanes-66840
```
and then I have to run that last line to my xpanes session.

**Comment by dzg** [comment]
Sorry, it doesn't quite work...

I tried:
```
cmd1="'/Volumes/Common/_Automation/node Test/script.py' '/Volumes/Work/_Automation/queue/3' --option A"
cmd2="'/Volumes/Common/_Automation/node Test/script.py' '/Volumes/Work/_Automation/queue/4' --option B"
eval xpanes -e --debug `for _ in {1..3}; do echo \"$cmd1\"; done` $cmd2
```

This opened **7** panes. 4 of them ran `cmd1`, but the other 3 had fragments of commands.

xpanes showed:
```
xpanes:Debug: [2018-11-21_16:26:48] Options: '-e' '--debug' '-c' '{}'
xpanes:Debug: [2018-11-21_16:26:48] Arguments: ''"'"'/Volumes/Common/_Automation/node Test/script.py'"'"' '"'"'/Volumes/Work/_Automation/queue/3'"'"' --option A' ''"'"'/Volumes/Common/_Automation/node Test/script.py'"'"' '"'"'/Volumes/Work/_Automation/queue/3'"'"' --option A' ''"'"'/Volumes/Common/_Automation/node Test/script.py'"'"' '"'"'/Volumes/Work/_Automation/queue/3'"'"' --option A' '/Volumes/Common/_Automation/node Test/script.py' '/Volumes/Work/_Automation/queue/4' '--option' 'B'
[exited]
``` 

That's a lot of quotes!

**Comment by greymd** [comment]
```sh
cmd1="'/Volumes/Common/_Automation/node Test/script.py' '/Volumes/Work/_Automation/queue/3' --option A"
cmd2="'/Volumes/Common/_Automation/node Test/script.py' '/Volumes/Work/_Automation/queue/4' --option B"
```

and  it may work.
Additional escaping is also required for `$cmd2` because of `eval`

```sh
eval xpanes -e `for _ in {1..3}; do echo \"$cmd1\"; done` "\"$cmd2\""
```

yeah, lots of quotes ...
I noticed that this way is more simpler.

If you are using bash, try it.
```sh
xpanes -e "$(for _ in {1..3}; do echo "$cmd1"; done; echo "$cmd2")"
```

In case of zsh, it may work.
```sh
xpanes -e < <(for _ in {1..3}; do echo "$cmd1"; done; echo "$cmd2")
```

**Comment by dzg** [comment]
Yes, success! 
```shell
xpanes -e "$(for _ in {1..3}; do echo "$cmd1"; done; echo "$cmd2")"
```
This works!

Arigato!!

**Comment by dzg** [comment]
> ```shell
> cmd1="'/Volumes/Common/_Automation/node Test/script.py' '/Volumes/Work/_Automation/queue/3' --option A"
> cmd2="'/Volumes/Common/_Automation/node Test/script.py' '/Volumes/Work/_Automation/queue/4' --option B"
> ```
> 
> and it may work.
> Additional escaping is also required for `$cmd2` because of `eval`
> 
> ```shell
> eval xpanes -e `for _ in {1..3}; do echo \"$cmd1\"; done` "\"$cmd2\""
> ```
> 
> yeah, lots of quotes ...
> I noticed that this way is more simpler.
> 
> If you are using bash, try it.
> 
> ```shell
> xpanes -e "$(for _ in {1..3}; do echo "$cmd1"; done; echo "$cmd2")"
> ```
> 
> In case of zsh, it may work.
> 
> ```shell
> xpanes -e < <(for _ in {1..3}; do echo "$cmd1"; done; echo "$cmd2")
> ```
