### ISSUE TITLE
Getting the index of each pane

### ISSUE THREAD

**Issue by brasilikum** [greymd/tmux-xpanes#117]
Hey, thank you very much for this tool, I am using it almost daily now!

I am having some issues with commands that are not meant to be run in parallel and therefore interfering with each other (in my case the aws cli)

I was thinking of a workaround where I would `sleep 10 * PANE_INDEX; command` to offset the commands a little. Is it currently possible to get this index somehow?

Best

**Comment by greymd** [comment]
Hi, thank you for using xpanes !

Unfortunately, `xpanes` does not provide such the feature.

The workaround is calling `tmux` in the `-c` option and get the index number of pane.

* `tmux display -pt "${TMUX_PANE}" "#{pane_index}"`

For example,

```bash
xpanes -sc 'idx=$(tmux display -pt "${TMUX_PANE}" "#{pane_index}"); sleep $idx; echo {}' A B C D
```

In above example, the variable `idx` has the index number (0, 1, ...) for each pane.
Therefore, `sleep $idx` waits particular seconds.

On the other hand, I wonder it would be helpful if xpanes could provide the feature to set the intervals for each command.
I am curious what aws cli command did you try, by the way.

Thanks

**Comment by brasilikum** [comment]
Hey @greymd,
that sounds like a great workaround! I am not sure if it's necessary to provide this feature directly but providing a $INDEX and showing in the examples how to use it to achieve "staggering" would certainly provide some benefit

I sometimes get this problem while deploying to two different environments. Also if I want to ssh into multiple machines at once via eb ssh (yes I know, bad practice), I end up logging into the same machine x times because I do a `eb use {}` before, which changes a file in the .aws folder
So by sleeping a little I can achieve the following behavior:

globally change to environment A
ssh into A on pane 1
globally change to environment B
ssh into B on pane 2
...
execute command on all environments

**Comment by greymd** [comment]
Hi @brasilikum,

It is good to know the use case that requires the index number of pane.
I've just updated [README.md](https://github.com/greymd/tmux-xpanes#get-index-number).
I am sure it is worth adding the example to the document 👍

By the way,  I think it seems like almost all sub-commands of `eb` can accepts the environment name. `EB CLI 3.14.13` on my environment shows..

```
$ eb ssh --help
usage: eb ssh <environment_name> [options ...]
```
I might be possible to log in to multiple environment with `eb ssh {}`.
This is just for your information.

Let me close the issue for now.
Thank you !

**Comment by greymd** [comment]
FYI:
Recently, [v4.1.0](https://github.com/greymd/tmux-xpanes/releases/tag/v4.1.0) was released and it got the new feature called `-B` option.
With this feature, xpanes can be highly improved with `alias` and it would help you in that use case.
See https://github.com/greymd/tmux-xpanes/wiki/Alias-examples#get-index-number.

thanks

**Comment by brasilikum** [comment]
So nice, thank you very much!

**Comment by brasilikum** [comment]
For anyone looking this up for reference: you can pass the environment into eb deploy `environment` but it still cannot handle concurrency until you uploaded the application package. 

I ended up doing:
```
_tmp='INDEX=`tmux display -pt "${TMUX_PANE}" "#{pane_index}"`'                                                                                                      
alias xpanes="xpanes -B '${_tmp}'"
xpanes -c 'sleep $((20*$INDEX)) && eb deploy {} --timeout 30' env1 env2
```
