### ISSUE TITLE
Suggestion: Red color when pane is dead

### ISSUE THREAD

**Issue by tzachshabtay** [greymd/tmux-xpanes#122]
We run `xpanes` with a lot of micro-services and sometimes it's hard to see when a service dies. It would be nice if the `Pane is dead` message was colored red, or even better, it the pane name label background changed from green to red when that happens.

**Comment by greymd** [comment]
Great idea!
I think I can add new [shell variable](https://github.com/greymd/tmux-xpanes#shell-variables) to change the format of the default message.
And it might be better to make the default message have red background.

I will work on it next release.
But it may take much time due to my another work.
Stay tuned.
Or, pull requests are always welcome if you hope :)

**Comment by greymd** [comment]
> even better, it the pane name label background changed from green to red when that happens.

Executing `tmux select-pane -T "#[bg=red,fg=black] #T #[default]"` is the workaround as of xpanes v4.1.0

```sh
$ xpanes -tsc 'YOUR_COMMAND; tmux select-pane -T "#[bg=red,fg=black] #T #[default]"' _
```

**Comment by greymd** [comment]
Default message can be changed by `TMUX_XPANES_PANE_DEAD_MESSAGE` variable.
See https://github.com/greymd/tmux-xpanes#tmux_xpanes_pane_dead_message

This feature was released at [v4.1.1](https://github.com/greymd/tmux-xpanes/releases/tag/v4.1.1).

**Comment by tzachshabtay** [comment]
Great, thanks!
When are you going to upload to brew?

**Comment by greymd** [comment]
After this PR is merged, you'll be able to use it. (Many thanks @BePsvPT !).
https://github.com/Homebrew/homebrew-core/pull/39580

Have a ☕️ and wait.

**Comment by tzachshabtay** [comment]
While waiting I tried using the `select-pane` as you described but it doesn't seem to work correctly -> it sometimes marks the wrong panes in red.
From looking at `man tmux` I didn't see what's the behavior for `select-pane` when you don't provide a target pane with `-t`, but I guess it doesn't do what we want it to do (i.e to use the pane we're running from).
I didn't see a built-in way in tmux to get the pane id from which we're running, is there maybe a variable that xpanes provides for this?

**Comment by greymd** [comment]
As you pointed out, my workaround does not work as expected, sorry.

> I didn't see a built-in way in tmux to get the pane id from which we're running, is there maybe a variable that xpanes provides for this?

We can get index number of pane like this.
```
tmux display -pt "${TMUX_PANE}" "#{pane_index}"
```

And, this workaround works in my environment.
```
$ xpanes -tsc 'INDEX=`tmux display -pt "${TMUX_PANE}" "#{pane_index}"`; sleep {}; tmux select-pane -t $INDEX -T "#[bg=red,fg=black] #T #[default]"' 1 2 3 4 5 6 7
```

To register the `alias` of `xpanes` command might be helpful for you.
https://github.com/greymd/tmux-xpanes/wiki/Alias-examples#get-index-number
