### ISSUE TITLE
Using a Jumphost in .zshrc for xpanes

### ISSUE THREAD

**Issue by ghost** [greymd/tmux-xpanes#133]
Like discussed [here](https://serverfault.com/questions/979482/how-to-call-a-host-from-ssh-config-in-zsh-by-alias-together-with-1 ): 

My primary Usecase is to use xpanes trough a Jumpost, And Call it via ZSH Alias Like for example:
`alias xpanes-jumphost="xpanes --log=~/log --ssh -i $HOME/.ssh/id_rsa -J $1 $(cat ~/.ssh/hosts/xpanes-hostlist)"`

Suspectus answered the following:
`xpanes-jumphost()
{
   [[ ! "$1" ]] && return  # return if no parameter
   xpanes --log=~/log --ssh -i $HOME/.ssh/id_rsa -J $1 $(cat ~/.ssh/hosts/xpanes-hostlist)`
}
`

But I get This instead:

` /home/user/.zshrc:189: parse error near `()' ` 
Maybe because of `$(cat ~/.ssh/hosts/xpanes-hostlist)i`

is this Setup possible to achive with xpanes? Would be incredable awesome, if so!

Isn't xpanes a wrapper for SSH and should be able to use also the -J Flag or are we on the wrong track with this Post?

Any Kind of Help Highly appreciated!

Keep Up the Good Work, - Tinfoil-hat

**Comment by greymd** [comment]
Hi,

I believe that you should use `-c "ssh ..."` instead of `--ssh`.
Because `-J` is provided by `ssh` (With `--ssh`, any options of `ssh` cannot be used).
I guess, what you want to do is something like this.

```zsh
xpanes-jumphost()
{
  [[ ! "$1" ]] && return
  xpanes --log=~/log -c "ssh -i $HOME/.ssh/id_rsa -J $1 {}" $(cat ~/.ssh/hosts/xpanes-hostlist)
}
```

**Comment by ghost** [comment]
Perfect! Thank you so much, works like charm now
