### ISSUE TITLE
Use GitHub Actions

### ISSUE THREAD

**Issue by greymd** [greymd/tmux-xpanes#140]
Let us consider to use GitHub Actions.
I expect testing time becomes shorter than usual since it can run many processes parallelly than TravisCI. I guess.

**Comment by greymd** [comment]
It is impossible to migrate tests to GitHub Actions.
Here is the current testing environment provided by TravisCI.
tmux session can be opened since pseudo-terminal is provided.

![Screenshot 2020-04-28 at 23 49 43](https://user-images.githubusercontent.com/3874767/80546222-01c11500-89ad-11ea-9278-7f171b720135.png)

In GitHub Actions however, all the standard stream are connecting to pipes.

![Screenshot 2020-04-29 at 00 03 33](https://user-images.githubusercontent.com/3874767/80546343-477ddd80-89ad-11ea-92f7-af524b14e099.png)

We cannot simulate tmux-xpanes because tmux session cannot be opened properly.
Let me give up GitHub Actions.

**Comment by greymd** [comment]
I've tried more times. However tmux cannot attach the session.

![Screenshot 2020-04-30 at 21 33 59](https://user-images.githubusercontent.com/3874767/80756420-5e960a00-8b2a-11ea-88be-25224a414f37.png)

**Comment by nicm** [comment]
That message means you need to set `TERM`, try setting `TERM=ansi` or `TERM=xterm`.

But you would be better if possible just to have tmux detached, although perhaps that is impossible with how your tests work.

**Comment by greymd** [comment]
thx @nicm
`tmux` works on GitHub Actions and test is passed!

<img width="734" alt="Screenshot 2020-05-01 at 22 58 24" src="https://user-images.githubusercontent.com/3874767/80844968-df730580-8bff-11ea-923e-3b662ba03124.png">

**Comment by greymd** [comment]
Migration is over.
tmux-xpane's test had taken over 6 hours before.

https://travis-ci.org/github/greymd/tmux-xpanes/builds/676944678
![Screenshot 2020-05-06 at 15 01 27](https://user-images.githubusercontent.com/3874767/81186929-4cddb800-8fab-11ea-9f6c-8db26e5c18c1.png)

However, it only takes less than 30 minutes now.

https://github.com/greymd/tmux-xpanes/actions/runs/97156917
![Screenshot 2020-05-06 at 15 06 54](https://user-images.githubusercontent.com/3874767/81186939-4fd8a880-8fab-11ea-876c-942e6e4173c2.png)

Finally tmux works inside of GitHub Actions by using `script`, setting `TERM` variable and providing terminal size with `stty` like this.

```bash
script -e -c /bin/bash -c 'stty rows 40 cols 80;TERM=xterm bash ./test.sh'
```

**Comment by greymd** [comment]
As you can see [here](https://github.com/greymd/tmux-xpanes/actions?query=workflow%3Atest), GitHub Actions works perfectly from [v4.1.2](https://github.com/greymd/tmux-xpanes/releases/tag/v4.1.2)
