### ISSUE TITLE
Tmux version detection fails 

### ISSUE THREAD

**Issue by Salamandar** [greymd/tmux-xpanes#143]
Tmux version is `next-3.2`, and xpanes constantly fails on this : 

```
xpanes:Warning: -t option cannot be used by tmux version less than 2.3. Disabled.
xpanes:Warning: 'xpanes' may not work correctly! Please check followings.
* tmux is installed correctly.
* Supported tmux version is installed.
  Version 1.8 and over is officially supported.
```

It seems the `next-` breaks the version comparison function.

**Comment by greymd** [comment]
See #119 

### Workaround
1. Make sure xpanes is v4.1.0 or more.
2. Add this statement to your shell's `~/.*rc` file.

```
export TMUX_XPANES_TMUX_VERSION=3.2
```

The warning message will be gone.

**Comment by Salamandar** [comment]
Thanks.
