### ISSUE TITLE
Question: Is there any way to support "current pane" options?

### ISSUE THREAD

**Issue by TheKevJames** [greymd/tmux-xpanes#196]
I'm not sure yet if this is a feature request or if this is already supported and I've missed the option!

---

*Background:*

My tmux config is set up to use a pane variable (`set-option -p @foobar`) to set custom titles/colors/etc. This allows me to do things like turning panes red if they are pointing at production servers, set pane titles to include hostnames when I ssh within tmux, etc. I accomplish this by overwriting builtin commands and setting tmux variables accordingly per-pane.

Example:
```
# .bashrc
declare -A HOSTNAME_COLORS=(["my-production-server"]=red)
function ssh() {
    HOSTNAME="${@:$#}"
    tmux set-option -p @custom_pane_color "${HOSTNAME_COLORS[$HOSTNAME]:-terminal}"
    command ssh "$@"
    tmux set-option -p @custom_pane_color "terminal"
}

# .tmux.conf
set-option -g @custom_pane_color 'terminal'
set -g pane-border-format "#[fg=#{@custom_pane_color},bg=terminal] #{pane_index} "
```

In the above case, the title of each pane is just it's index in my foreground font, but when I run `ssh my-production-server` the pane title switches to red while I'm connected.

---

*Problem:*

Unfortunately, I can't get `xpanes` to work with this workflow. If I run, for example:
```
xpanes -c "ssh {}" "my-staging-server" "my-production-server"
```
then only pane 0 gets it's title set as it seems to be considered the "current pane" for the purpose of the `set-option -p` command.

This is also true if `set-option` is included explicitly within the xpanes command:
```
xpanes -c "tmux set-option -p @custom_pane_title '{}'; ssh {}" "my-staging-server" "my-production-server"
```

**Is there any way to have xpanes update the "current" pane when it runs these commands?**

**Comment by greymd** [comment]
> Is there any way to have xpanes update the "current" pane when it runs these commands?

This must be accomplished by utilizing multiple options.
Could you try this one?

```sh
xpanes --interval=0.1 -B 'tmux select-pane -t $TMUX_PANE' -c "ssh {}" "my-staging-server" "my-production-server"
```

The `--interval` option introduces a delay, waiting for the specified seconds between each pane split.
The `-B` option executes a given command just before the `-c` option is run for each pane.
Thus, the above command activates each pane in sequence.
Once a specific pane becomes active and the `ssh` command, which is redefined as a shell function, is executed, the next pane becomes the "current pane" and the same process is repeated.

**Comment by TheKevJames** [comment]
Can confirm your command works, thanks! Doesn't handle the "exiting the ssh connections in tmux synchronize mode clears the title" part, but that's a) not a big deal, and b) more a tmux thing than having anything to do with xpanes.

**Comment by plutonium-239** [comment]
Hey, I need some help related to running a `source`'d function in `xpanes`.

I call `xpanes` from inside `main.sh`:
```sh
var=something
source myfunctions.sh # has a function foo which takes an argument and also refers to ${var}

list_inp=(First Second ...)

xpanes -c "foo {}" ${list_inp[@]}

...
```

What this results in is the inputs being passed correctly to the pane but the function being undefined.
I tried the above answer, but it is still undefined inside the panes

Am I missing something?
Do I need to source from myfunctions again inside the `-B` argument? I don't really know why because by sourcing myfunctions.sh into main.sh, we are essentially making the functions visible inside main.sh, and that should automatically be visible from all the panes right?
