### ISSUE TITLE
Adding a RPM SPEC file

### ISSUE THREAD

**Issue by mpatenaude** [greymd/tmux-xpanes#71]
Hi Yasuhiro,

Thanks for this excellent tmux utility!

I created a "basic" RPM SPEC file to package this for RHEL based systems.  I'm using CentOS 7 and it works very well with the distribution included tmux (v1.8).

The generated RPM install the following file tree:

```
/
|-- usr
|    |-- bin
|    |   |-- tmux-xpanes -> ./xpanes
|    |   `-- xpanes
|    `-- share
|        |-- doc
|        |   `-- tmux-xpanes-2.2.1
|        |       |-- CONTRIBUTING.md
|        |       `-- README.md
|        |-- licenses
|        |   `-- tmux-xpanes-2.2.1
|        |       `-- LICENSE
|        `-- man
|            `-- man1
|                |-- tmux-xpanes.1.gz -> xpanes.1.gz
|                `-- xpanes.1.gz
...
```

If you think this can be useful to others, I can make a pull request or you can copy it directly from my fork: https://github.com/mpatenaude/tmux-xpanes/blob/master/tmux-xpanes.spec

Best,
Math

**Comment by greymd** [comment]
Hi Math,
Thank you very much for your fantastic suggestion!
I believe it would be helpful for rpm users.
I check and merge it if you send the PR.

Thanks,
greymd

**Comment by mpatenaude** [comment]
Excellent, PR #72 

Thanks,
Math.

**Comment by carlwgeorge** [comment]
I'm looking at submitting this for inclusion in Fedora and EPEL.  I'm using @mpatenaude's spec file as a starting point, and adjusting it for the current Fedora packaging guidelines.

Since the command is `xpanes`, what do you think about just calling the package xpanes instead of tmux-xpanes?

**Comment by carlwgeorge** [comment]
I have built this as xpanes in a [copr repository](https://copr.fedorainfracloud.org/coprs/carlwgeorge/reviews/).  It provides the name tmux-xpanes as well, so it can be installed by either name.  Fedora users can try it out with these commands:

```
dnf copr enable carlwgeorge/reviews
dnf install xpanes
```

@greymd Let me know if you'd like the package name reverted back to tmux-xpanes, otherwise I'm ready to submit the spec file for inclusion in Fedora.  After it's approved, I can request EPEL branches to make it available for RHEL and CentOS users.

**Comment by carlwgeorge** [comment]
Submitted: https://bugzilla.redhat.com/show_bug.cgi?id=1759206

**Comment by greymd** [comment]
Hi @carlwgeorge ,
Firstly, thank you very much for using the xpanes.

> I'm looking at submitting this for inclusion in Fedora and EPEL. 

I am really appreciated for your suggestion !

> Since the command is xpanes, what do you think about just calling the package xpanes instead of tmux-xpanes?

I don't mind the package name to be changed to whatever the guideline/community would accept 😉

**Comment by greymd** [comment]
@carlwgeorge If the package name in the spec file is better to be xpanes rather than tmux-xpanes from the point of view of the maintainability, please send the new pull-request.
As I mentioned, I don't stick to the name of the package.
