### ISSUE TITLE
how to execute different command after got split windows

### ISSUE THREAD

**Issue by dawei101** [greymd/tmux-xpanes#73]
Is there anyway to run different command after xpanes runs up

**Comment by greymd** [comment]
Hi,

There is no such the feature in tmux-xpanes.
Type commands on the panes one by one (by using tmux's key binding) after the window is splitted into panes.

FYI, `-d` option helpful in such the case.
tmux-xpanes makes synchronize all the inputs of the panes by default.
But the option suppresses it.

```
$ xpanes -d 1 2 3 4
```

**Comment by dawei101** [comment]
Thanks
