### ISSUE TITLE
[curiosity] compare/contrast/synergy/etc with `parallel --tmuxpane`

### ISSUE THREAD

**Issue by emanresusername** [greymd/tmux-xpanes#80]
i guess this is more of an open ended prompt, i've come across these two in the same breath of internet searching on a couple occasions, curious how/if they relate/conflict/supplement/etc?
https://www.gnu.org/software/parallel/man.html#tmuxpane

**Comment by greymd** [comment]
Wow, I did not know GNU parallel provides such the option.
Thank you for your information!

I've tried `parallel` command and I am sure that there are some different policies and features between `parallel --tmuxpane` and `xpanes`.

But, I think, most different point is `tmux-xpanes` is also designed to help users operate interactive screens.

### Better for `tmux-xpanes`

For example, it is impossible for `parallel` to connect multiple servers/containers and make changes to all of them simultaneously  (`parallel` closes panes automatically).

```
## Works
$ xpanes -c 'ssh {}' host1 host2 host3

## Does not work
$ parallel --fg --tmuxpane 'ssh {}' ::: host1 host2 host3
```

### Better for `parallel`

In contrast, it might be better to use `parallel` to run the jobs more effectively.
Originally, `parallel` is designed to run jobs in "parallel" and it has some useful features for them. For example, it can specifies the maximum number of process.

**Comment by emanresusername** [comment]
curiosity satisfied :) thanks!
