### ISSUE TITLE
Set pane ssh title

### ISSUE THREAD

**Issue by linuxmail** [greymd/tmux-xpanes#81]
Hi,

since I can't use mssh anymore, I learned to love tmux, because of xpanes :-) The only thing I miss under my Linux (bash), is to know, which pane is which (ssh) host. If I connect to 20 hosts or more, I have only the hostname, which you don't see always.
Is there a way to put a small bar under every pane which shows the hostname ?

cu denny

**Comment by greymd** [comment]
Hi @linuxmail ,
Thank you for using tmux-xpanes 😸 !

> put a small bar under every pane

As far as I know, both tmux and tmux-xpanes do not have such the feature for now.
But I can understand the matter, and I think it would be really helpful if such the feature existed.

FYI, usually, I update `PS1` environment variable when I face same issue.
If you use bash, it may be helpful.

```bash
$ ssh -t host01 'export PS1="[host01] \W $ "; bash --norc -i'
```

It puts the "host01" at the beginning of the interactive screen like this.

```bash
[host01] ~ $ 
```

Therefore, this command line would put the target hostname at the beginning of each pane.
It may help you identify the pane and its target host.

```bash
$ xpanes -c 'ssh -t {} "export PS1=\"{} \W $ \";bash --norc -i"' {host01..host20}
```

**Comment by greymd** [comment]
I came up with a terrible idea 👼 
Open new tmux sessions and set the session name on the destination server.
A small bar that has its host name can be placed on each pane !

```bash
xpanes -c 'ssh -t {} "tmux new -s {}"' cac0{1..6}
```

<img width="1280" alt="screen shot 2018-03-20 at 18 53 09" src="https://user-images.githubusercontent.com/3874767/37647805-8b3ceed6-2c70-11e8-8f05-77a5c24a870b.png">

Just a kidding, hahaha.

**Comment by greymd** [comment]
It seems that tmux 2.3 and upper version got the feature to customize each pane's border design with `pane-border-format` property. It might be possible to display the hostname.
Stay tuned.

**Comment by linuxmail** [comment]
hi,

whoooo, its incredible :1st_place_medal:

**Comment by greymd** [comment]
@linuxmail 
New option `-t` was released 👍

![v3new](https://user-images.githubusercontent.com/3874767/41632080-19336600-7430-11e8-96a4-eeb3c5bb5a86.gif)

https://github.com/greymd/tmux-xpanes/releases

**Comment by linuxmail** [comment]
WHOOOOO that is sooo whooo AWESOME. Thank you so much !!

**Comment by paxperscientiam** [comment]
To customize this title, I've found that this function works for setting a custom xpane title:

```bash
function title {
    echo -ne "\033]0;"$*"\007"
}
```

Example I use with an iTerm profile:
```shell
command xpanes -t -d -l eh -c "{}" "title money && emacs -s money -- $LEDGER_FILE_PERSONAL" "title accounting && clear"
```

source: https://superuser.com/a/599156
