### ISSUE TITLE
Adding Ubuntu 18.04 Bionic distribution to PPA

### ISSUE THREAD

**Issue by erolg** [greymd/tmux-xpanes#83]
hi, 

Xpane is not available for new ubuntu distros, 18.04 and 17.10 in PPA

http://ppa.launchpad.net/greymd/tmux-xpanes/ubuntu/dists/

  | artful/ | 2018-01-18 06:41 | - |  
  | devel/ | 2018-01-18 06:41 | - |  
  | trusty/ | 2018-01-18 06:28 | - |  
  | vivid/ | 2018-01-18 06:41 | - |  
  | xenial/ | 2018-01-18 06:41 | - |  
  | yakkety/ | 2018-01-18 06:41 | - |  
  | zesty/ | 2018-01-18 06:41 | - |

**Comment by greymd** [comment]
Hi,

Thank you for reporting this issue!

I will work on it probably next month (pardon me, I do not have enough time to work on it this month).

**Comment by greymd** [comment]
Done. Cosmic has also been supported.
Sorry for inconvenience 😇 

http://ppa.launchpad.net/greymd/tmux-xpanes/ubuntu/dists/
  | artful/ | 2018-01-18 06:41 | - |  
  | bionic/ | 2018-06-08 20:34 | - |  
  | cosmic/ | 2018-06-08 20:34 | - |  
  | devel/ | 2018-06-08 20:34 | - |  
  | trusty/ | 2018-01-18 06:28 | - |  
  | vivid/ | 2018-01-18 06:41 | - |  
  | xenial/ | 2018-01-18 06:41 | - |  
  | yakkety/ | 2018-01-18 06:41 | - |  
  | zesty/ | 2018-01-18 06:41 | - |
