### ISSUE TITLE
Have Last Pane Picked Rather than the First as an Option 

### ISSUE THREAD

**Issue by shaneholloman** [greymd/tmux-xpanes#84]
Firstly thank you and wow... this a lovely Tmux function indeed
We have stage of capture machines (14 of them)
The last pane what we usually like to type into because it's usually the biggest window.

I run `xpanes -c "ssh {}" linuxcapture{01..14}`
What would I run to always have the last window picked instead of the first

I guess there would be 2 ways?
- Setting here: `.bashrc`
- Appended option here: `xpanes -c "ssh {}" linuxcapture{01..14}`

**Installed like this** As we are on Ubuntu 18.04  
```bash
eighti@thor:~/.xpanes$ sudo ./install.sh 
[sudo] password for eighti: 
install -d /usr/local/bin
install -m 755 /home/eighti/.xpanes/bin/xpanes /usr/local/bin/xpanes
install -m 755 /home/eighti/.xpanes/bin/tmux-xpanes /usr/local/bin/tmux-xpanes
install -d /usr/local/share/man/man1
install -m 755 /home/eighti/.xpanes/man/xpanes.1 /usr/local/share/man/man1/xpanes.1
install -m 755 /home/eighti/.xpanes/man/tmux-xpanes.1 /usr/local/share/man/man1/tmux-xpanes.1
eighti@thor:~/.xpanes$ which xpanes
/usr/local/bin/xpanes
eighti@thor:~/.xpanes$ 
```

![xpanes with last panes always picked](https://user-images.githubusercontent.com/1563909/40403203-727d7d3c-5ea4-11e8-9116-0ea7832f6a1f.png)

**Comment by greymd** [comment]
Hi @shaneholloman ,

Thank you for using tmux-xpanes and your suggestion!
Sorry for late reply.

Please see the next comment.
I would like to create new feature that allows users to pick the last pane.

* * *
FYI
Here is the workaround as of v2.2.3.
Define the bash alias to select the last pane, and put it at the beginning of `-c` option's argument.
tmux-xpanes picks a pane that has biggest internal index number defined by tmux.
Therefore,  the last one is supposed to be picked with the following alias.

```bash
alias picklast="tmux list-pane -F '#P'  | tail -n1 | xargs tmux select-pane -t"
```
Add it to `~/.bashrc` and try it.

```bash
~ $ xpanes -c "picklast; ssh {}" server{01..14}
```

<img width="1440" alt="screen shot 2018-06-08 at 8 15 06 pm" src="https://user-images.githubusercontent.com/3874767/41176552-c4958ebe-6b58-11e8-8b89-edac5133ccea.png">

**Comment by greymd** [comment]
I am planning to implement new feature #85.
And I hope it can solve this issue.

If #85 is implemented, last pane is always picked.
What user have to do is to state following bash script in `~/.bashrc`.

```
alias picklast="tmux list-pane -F '#P'  | tail -n1 | xargs tmux select-pane -t"
alias xpanes="xpanes -c picklast"
```

**Comment by greymd** [comment]
I have new idea.
how about new option like this ?
https://github.com/greymd/tmux-xpanes/issues/99#issue-347656952

> The last pane what we usually like to type into because it's usually the biggest window.

It seems that, it is better to have the option to specify not only the pane index, but also the pane size.
If you have any good idea, please inform me.

**Comment by greymd** [comment]
Hi @shaneholloman !

New version [v4.0.0](https://github.com/greymd/tmux-xpanes/releases/tag/v4.0.0) makes the each pane size as same as possible.

See this screen capture.
This is latest xpanes does.
<img width="1440" alt="screen shot 2019-03-01 at 1 04 35 am" src="https://user-images.githubusercontent.com/3874767/53609314-37f2e100-3bbe-11e9-932d-fcd465690d96.png">


Old algorithm is...
<img width="1440" alt="screen shot 2019-03-01 at 1 04 48 am" src="https://user-images.githubusercontent.com/3874767/53609290-290c2e80-3bbe-11e9-874e-5bf0623c1852.png">


I believe, most of the cases, it is not necessary to select the big (or wide) pane.
In addition, I am not confident that this feature is worth implementing or not.
If you hope this feature, please see #99.

Let me close this issue for now.
But if you have any further concerns, please re-open it anytime or create new issue 👍 

Thanks!

**Comment by greymd** [comment]
FYI:
Hi @shaneholloman 
Recently, [v4.1.0](https://github.com/greymd/tmux-xpanes/releases/tag/v4.1.0) was released and it got the new feature called `-B` option.
With this feature, xpanes can be highly improved with `alias` and it would help you in that use case.
See https://github.com/greymd/tmux-xpanes/wiki/Alias-examples#select-biggest-pane-by-default

**Comment by shaneholloman** [comment]
@greymd that is a thing of beauty! Nice work!
