### ISSUE TITLE
Start panes without sourcing `~/.zshrc`

### ISSUE THREAD

**Issue by segeljakt** [greymd/tmux-xpanes#90]
I think it would be nice if there was an option to launch each xpane without sourcing the `~/.zshrc` or `~/.bashrc` as it would improve the startup time. I'm not sure how to do it with tmux, but `zsh -f` will launch `zsh` without loading the `~/.zshrc`.

**Comment by greymd** [comment]
In my understanding, whether the tmux loads the "rcfile" like `~/.bashrc` or not is depending on the user's configures. `tmux` and `xpanes` would work without sourcing `~/.zshrc` if `set-option -g default-command "zsh -f"` is stated in the `~/.tmux.conf`.

By the way, another user also hopes that `xpanes` executes the command without shell-dependent settings (issue #89) and I am working on it. It may be what you want.

**Comment by segeljakt** [comment]
Ok, it sounds interesting!

**Comment by greymd** [comment]
Now [v3.1.0](https://github.com/greymd/tmux-xpanes/releases/tag/v3.1.0) got the new option `-s` to open panes without sourcing `~/.zshrc` file. Please try it!

If it does not satisfies you, plz re-open it.

**Comment by greymd** [comment]
cool, isn't it?
![movie](https://user-images.githubusercontent.com/3874767/43615818-6489f350-96b1-11e8-8c32-f89f591c89f9.gif)

**Comment by klassegeljakt** [comment]
It looks awesome! I'll try it as soon as homebrew-core merges the PR

**Comment by segeljakt** [comment]
It looks awesome! I'll try it asap when homebrew-core merges the PR

**Comment by segeljakt** [comment]
I just tried it, works really well, nicely done
