### ISSUE TITLE
Remove perl dependancy

### ISSUE THREAD

**Issue by ScrumpyJack** [greymd/tmux-xpanes#91]
If would be good to remove the dependency on perl and keep to bash only. 

This would allow for a smaller payload and it would be usable in micro servers/embedded linux where there is no perl available, or systems where perl/python is not allowed.

**Comment by greymd** [comment]
yeah, that's right.
stay tuned :)

**Comment by greymd** [comment]
tmux-xpanes [v3.0.1](https://github.com/greymd/tmux-xpanes/releases/tag/v3.0.1) is no longer depending on the perl.
The source code consists only of pure bash script (v3.2 and later) and some POSIX compliant UNIX commands.
